-- MySQL Script generated by MySQL Workbench
-- Fri May 27 13:52:07 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema strom
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `strom` ;

-- -----------------------------------------------------
-- Schema strom
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `strom` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
SHOW WARNINGS;
USE `strom` ;

-- -----------------------------------------------------
-- Table `strom`.`t_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `strom`.`t_user` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `strom`.`t_user` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '用户id',
  `user_name` VARCHAR(145) NULL COMMENT '用户名',
  `pwd` VARCHAR(245) NULL COMMENT '密码',
  `age` INT NULL COMMENT '年龄',
  `phone` VARCHAR(145) NULL COMMENT '电话',
  `email` VARCHAR(145) NULL COMMENT '邮箱',
  `open_id` VARCHAR(145) NULL COMMENT '微信绑定时的openid',
  `addr` VARCHAR(445) NULL COMMENT '地址',
  `company` INT NULL COMMENT '公司',
  `department` INT NULL COMMENT '部门',
  `position` INT NULL COMMENT '职位',
  `user_type` INT NULL COMMENT '用户状态,1:新注册用户,2:邮箱未验证,3:电话未验证,4:微信未认证',
  `is_lock` INT NULL COMMENT '用户的可使用状态,1:正常,2:锁定',
  `add_time` VARCHAR(145) NULL COMMENT '添加时间',
  `update_time` VARCHAR(145) NULL COMMENT '更新时间',
  `remark` VARCHAR(245) NULL COMMENT '备注信息',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '用户表';

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `strom`.`t_menu`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `strom`.`t_menu` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `strom`.`t_menu` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(145) NULL,
  `description` VARCHAR(245) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
